name: Build FASTAPI Docker Image

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Docker
        run: sudo apt-get update && sudo apt-get upgrade &&  sudo apt-get install -y docker.io

      - name: Build Docker Image
        run: docker build -t ${{vars.DOCKER_USERNAME}}/fastapi-mlflow:ci .

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u ${{vars.DOCKER_USERNAME}} --password-stdin
        # on veut eviter de dévoiler notre mot de passe
      
      - name: Push Docker Image
        run: docker push ${{vars.DOCKER_USERNAME}}/fastapi-mlflow:ci
